[package]
name = "sglab01_bin"
version = "0.1.3"
edition = "2024"
authors = ["num-bbro <num@bbro.jp>"]
description = "num sglab01_bin"
license = "MIT OR Apache-2.0"

[dependencies]
sglab01_lib = { path = "../sglab01_lib", version = "^0.1.1" }

